from pathlib import Path
p=Path('src/prototype.css')
s=p.read_text()
marker='/* ONE PRO MOBILE DRAWER + ORG CHAT 2026-09-17 */'
if marker not in s:
    s += r'''

/* ONE PRO MOBILE DRAWER + ORG CHAT 2026-09-17 */
.topbar-leading{display:flex;align-items:center;gap:9px;min-width:0}.mobile-menu-trigger{width:40px;height:40px;display:grid;place-items:center;flex:0 0 auto;border:1px solid var(--line);border-radius:12px;background:var(--surface);color:var(--text)}
.mobile-nav-overlay{position:absolute;z-index:55;inset:0;background:#08091280;backdrop-filter:blur(4px);animation:mobile-nav-fade .18s ease both}.mobile-nav-drawer{position:absolute;inset:0 auto 0 0;width:min(86%,330px);display:flex;flex-direction:column;padding:calc(22px + env(safe-area-inset-top)) 14px calc(18px + env(safe-area-inset-bottom));background:var(--surface);border-right:1px solid var(--line);box-shadow:18px 0 45px #0809122b;animation:mobile-nav-slide .22s cubic-bezier(.22,.8,.3,1) both}.mobile-nav-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:0 2px 14px}.mobile-nav-brand{display:flex;align-items:center;gap:10px;border:0;background:transparent;color:var(--text);text-align:left}.mobile-nav-brand>.desktop-brand-logo{display:block;width:40px;height:40px;border-radius:12px;background:url('/brand/one-pro-mark.svg') center/100% 100% no-repeat}.mobile-nav-brand>span:last-child{display:grid;gap:1px}.mobile-nav-brand strong{font-size:15px}.mobile-nav-brand small{font-size:9px;color:var(--muted)}.mobile-nav-scope{display:grid;gap:3px;margin:0 2px 12px;padding:13px 14px;border:1px solid var(--line);border-radius:14px;background:var(--surface-2)}.mobile-nav-scope span{font-size:8px;letter-spacing:.1em;font-weight:900;color:var(--purple-2)}.mobile-nav-scope strong{font-size:13px}.mobile-nav-scope small{font-size:9px;color:var(--muted)}.mobile-nav-list{display:grid;gap:4px;overflow-y:auto;padding:2px 0 10px}.mobile-nav-list button{width:100%;min-height:48px;display:grid;grid-template-columns:28px 1fr 18px;align-items:center;gap:8px;border:0;border-radius:12px;padding:8px 10px;background:transparent;color:var(--muted);text-align:left}.mobile-nav-list button span{font-size:10px;font-weight:800}.mobile-nav-list button.active{background:color-mix(in srgb,var(--purple-2) 9%,var(--surface));color:var(--purple-2)}.mobile-nav-logout{margin-top:auto;min-height:46px;display:flex;align-items:center;justify-content:center;gap:8px;border:1px solid color-mix(in srgb,var(--danger) 24%,var(--line));border-radius:13px;background:color-mix(in srgb,var(--danger) 6%,var(--surface));color:var(--danger);font-size:10px;font-weight:850}
@keyframes mobile-nav-fade{from{opacity:0}to{opacity:1}}@keyframes mobile-nav-slide{from{transform:translateX(-28px);opacity:.5}to{transform:translateX(0);opacity:1}}

.org-chat-shell{height:min(690px,calc(100dvh - 210px));min-height:500px;display:grid;grid-template-columns:minmax(270px,330px) minmax(0,1fr);overflow:hidden;border:1px solid var(--line);border-radius:19px;background:var(--surface)}.org-contact-pane{min-width:0;display:grid;grid-template-rows:auto auto 1fr;border-right:1px solid var(--line);background:var(--surface)}.org-contact-head{padding:14px 15px 8px}.org-contact-head>div{display:flex;align-items:center;gap:9px;color:var(--purple-2)}.org-contact-head span{display:grid;gap:2px}.org-contact-head strong{font-size:13px;color:var(--text)}.org-contact-head small{font-size:8px;color:var(--muted)}.org-chat-search{margin:0 12px 10px;min-height:41px;display:flex;align-items:center;gap:7px;padding:0 10px;border:1px solid var(--line);border-radius:11px;background:var(--surface-2);color:var(--muted)}.org-chat-search input{width:100%;border:0!important;background:transparent!important;box-shadow:none!important;color:var(--text);font-size:10px;padding:0!important}.org-contact-list{overflow:auto;border-top:1px solid var(--line)}.org-contact-row{width:100%;min-height:70px;display:grid;grid-template-columns:40px minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px 12px;border:0;border-bottom:1px solid var(--line);background:transparent;color:var(--text);text-align:left}.org-contact-row:hover,.org-contact-row.active{background:color-mix(in srgb,var(--purple-2) 6%,var(--surface))}.org-contact-avatar{width:40px;height:40px;display:grid;place-items:center;border-radius:13px;background:color-mix(in srgb,var(--purple-2) 10%,var(--surface));color:var(--purple-2);border:1px solid color-mix(in srgb,var(--purple-2) 16%,var(--line))}.org-contact-copy{min-width:0;display:grid;gap:4px}.org-contact-copy strong{font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.org-contact-copy small{font-size:9px;color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.org-contact-row em{align-self:start;padding-top:4px;font-size:8px;color:var(--muted);font-style:normal}
.org-conversation-pane{min-width:0;display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:var(--surface-2)}.org-conversation-head{min-height:66px;display:flex;align-items:center;gap:10px;padding:10px 14px;border-bottom:1px solid var(--line);background:var(--surface)}.org-conversation-head>div{display:grid;gap:3px}.org-conversation-head strong{font-size:12px}.org-conversation-head small{font-size:8px;color:var(--muted)}.org-chat-back{display:none;width:36px;height:36px;place-items:center;border:0;border-radius:10px;background:var(--surface-2);color:var(--text)}.org-message-scroll{min-height:0;overflow-y:auto;padding:18px;display:flex;flex-direction:column;gap:8px;background:linear-gradient(180deg,color-mix(in srgb,var(--surface-2) 96%,transparent),var(--surface-2))}.org-bubble{align-self:flex-start;max-width:min(78%,620px);padding:9px 11px 7px;border:1px solid var(--line);border-radius:13px 13px 13px 4px;background:var(--surface);box-shadow:0 2px 6px #11111a08}.org-bubble.mine{align-self:flex-end;border-color:color-mix(in srgb,var(--purple-2) 20%,var(--line));border-radius:13px 13px 4px 13px;background:color-mix(in srgb,var(--purple-2) 10%,var(--surface))}.org-bubble p{margin:0 0 5px;font-size:10px;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}.org-bubble small{display:block;text-align:right;font-size:7px;color:var(--muted)}.org-chat-welcome,.org-chat-placeholder{min-height:100%;display:grid;place-items:center;align-content:center;gap:8px;padding:30px;text-align:center;color:var(--muted)}.org-chat-welcome strong,.org-chat-placeholder h2{margin:0;font-size:14px;color:var(--text)}.org-chat-welcome p,.org-chat-placeholder p{margin:0;max-width:360px;font-size:9px;line-height:1.55}.org-chat-composer{display:grid;grid-template-columns:minmax(0,1fr) 42px;gap:8px;padding:10px 12px;border-top:1px solid var(--line);background:var(--surface)}.org-chat-composer input{min-height:42px;width:100%;border:1px solid var(--line);border-radius:12px;padding:0 12px;background:var(--surface-2);color:var(--text);outline:none}.org-chat-composer button{width:42px;height:42px;display:grid;place-items:center;border:0;border-radius:12px;background:var(--purple-2);color:#fff}.org-chat-composer button:disabled{opacity:.45}.one-pro-shell.is-dark .org-bubble.mine{background:color-mix(in srgb,var(--purple-2) 22%,var(--surface))}

@media(max-width:899px){.org-chat-shell{height:calc(100dvh - 220px);min-height:470px;display:block}.org-contact-pane,.org-conversation-pane{height:100%}.org-conversation-pane{display:none}.org-chat-shell.has-selection .org-contact-pane{display:none}.org-chat-shell.has-selection .org-conversation-pane{display:grid}.org-chat-back{display:grid}.org-message-scroll{padding:14px 12px}.org-bubble{max-width:86%}.org-contact-row{min-height:68px}.org-chat-placeholder{display:none}}
@media(min-width:900px){.mobile-menu-trigger,.mobile-nav-overlay{display:none!important}.topbar-leading{gap:0}.org-chat-back{display:none!important}.org-chat-shell{height:min(720px,calc(100vh - 190px))}}
'''
    p.write_text(s)
